# Generated by Django 2.1.4 on 2019-01-21 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190122_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 2, 18, 33, 147271)),
        ),
    ]
