# Generated by Django 2.1.4 on 2019-01-21 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190122_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 2, 22, 31, 646275)),
        ),
    ]
