# Generated by Django 2.1.4 on 2019-01-21 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190122_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 2, 36, 19, 31105)),
        ),
    ]
