# Generated by Django 2.1.7 on 2019-03-11 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190122_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 13, 17, 24, 847446)),
        ),
    ]
