# Generated by Django 2.1.4 on 2019-01-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190122_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.TextField(blank=True),
        ),
    ]
